import type { JobFeedItem, JobSourceId, PostedAtConfidence } from "../shared/types";

export function makeTestJobFeedItem(overrides: Partial<JobFeedItem> = {}): JobFeedItem {
  return {
    id: 1,
    source: "linkedin" as JobSourceId,
    source_id: "job-1",
    title: "Backend Engineer",
    company: "Acme",
    location: "Remote",
    url: "https://example.com",
    posted_at: null,
    posted_at_ts: null,
    posted_at_confidence: "missing" as PostedAtConfidence,
    posted_text: null,
    description_excerpt_only: false,
    canonical_job_id: null,
    dedup_key: null,
    status: "ready",
    description: "Build APIs",
    seniority_level: null,
    employment_type: null,
    job_function: null,
    industry: null,
    heuristic_score: null,
    resume_generated: false,
    is_new: false,
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
    skills_score: 80,
    seniority_score: 70,
    domain_score: 60,
    location_score: 90,
    composite: 77,
    weighted_composite: 77,
    score_group: "Good",
    overqualified: false,
    matches: [],
    gaps: [],
    summary: null,
    dealbreaker_violations: [],
    ...overrides,
  };
}
